# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e83e5261b83b5a729355605d01c519e9a79ea36bfc45a53475d97ceed024ec756136a65b3fb44a6d40f77cc47898b464751fc08811509858d1ac60ae10e3ec95

test:
  secret_key_base: 7219e4d8da9b05b962db87c3dece32e8a12cc8048f1ed767f86fe9c4c3200c86837b7cf4c41f1cfe850be98ae3c561103315a4f125cc50670748949e067dce7c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
